### ISSUE TITLE
源码打包，启动CRASH

### ISSUE THREAD

**Issue by devil19** [JZ-Darkal/AndroidHttpCapture#17]
java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.darkal.networkdiagnosis/cn.darkal.networkdiagnosis.Activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.clans.fab.FloatingActionMenu.setClosedOnTouchOutside(boolean)' on a null object reference
                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2697)
                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2763)
                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1585)
                                                    at android.os.Handler.dispatchMessage(Handler.java:111)
                                                    at android.os.Looper.loop(Looper.java:207)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5939)
                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:817)
                                                 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.clans.fab.FloatingActionMenu.setClosedOnTouchOutside(boolean)' on a null object reference
                                                    at cn.darkal.networkdiagnosis.Activity.MainActivity.initFloatingActionMenu(MainActivity.java:909)
                                                    at cn.darkal.networkdiagnosis.Activity.MainActivity.onCreate(MainActivity.java:162)
                                                    at android.app.Activity.performCreate(Activity.java:6362)
                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2650)
                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2763) 
                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1585) 
                                                    at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                    at android.os.Looper.loop(Looper.java:207) 
                                                    at android.app.ActivityThread.main(ActivityThread.java:5939) 
                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956) 
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:817)

**Comment by darkal** [comment]
这个报错看起来像是butterknife初始化失败后造成的，检查下你的build.gradle中dependencies有没有
apt 'com.jakewharton:butterknife-compiler:8.2.1'
compile 'com.jakewharton:butterknife:8.2.1'

**Comment by paladinGu** [comment]
如果不把    apt 'com.jakewharton:butterknife-compiler:8.2.1'
                  compile 'com.jakewharton:butterknife:8.2.1'
删除
就会报这个错 android-apt plugin is incompatible with the Android Gradle plugin.  Please use 'annotationProcessor' configuration instead.
