### ISSUE TITLE
无法抓取微博app的https请求

### ISSUE THREAD

**Issue by caopengfei** [JZ-Darkal/AndroidHttpCapture#50]

**Comment by darkal** [comment]
at com.sina.weibo.net.m.a(WeiboHttpClient.java:82)
        at com.sina.weibo.net.j.a(NetUtilsProcessor.java:552)
        at com.sina.weibo.net.j.a(NetUtilsProcessor.java:440)
        at com.sina.weibo.net.i.a(NetUtils.java:554)
        at com.sina.weibo.net.i.a(NetUtils.java:529)
        at com.sina.weibo.net.i.a(NetUtils.java:518)
        at com.sina.weibo.net.i.a(NetUtils.java:513)
        at com.sina.weibo.net.i.a(NetUtils.java:508)
        at com.sina.weibo.net.f.c(NetEngine.java:9794)
        at com.sina.weibo.models.ShareConfigbean$1.run(ShareConfigbean.java:152)
        at com.sina.weibo.ae.h.run(PriorityRunnable.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
    Caused by: org.chromium.net.impl.NetworkExceptionImpl: Exception in CronetUrlRequest: net::ERR_CERT_AUTHORITY_INVALID, ErrorCode=11, InternalErrorCode=-202, Retryable=false
        at org.chromium.net.impl.CronetUrlRequest.onError(CronetUrlRequest.java:690)

**Comment by jp1017** [comment]
那该如何抓呢？tcpdump？ @darkal
